### ISSUE TITLE
More advanced installer?

### ISSUE THREAD

**Issue by davet2001** [sodacode/Windows-Syncthing-Installer#1]
I set up syncthing on Windows today manually, not realising that there was an installer.

I think it could be a much better user experience if:
- the installer set up syncthing as a service
- the installer added a URL shortcut to the web interface
- the installer was available on syncthing.net to download directly.

I'm happy to help if interested.

**Comment by sodacode** [comment]
Hi @davet2001, I literally just noticed that this issue was here.
This was a side-project for me, although I can implement those things.
Is the interest still there?

**Comment by codabrink** [comment]
I know this is a little late, but those are good ideas.
I'll see if I can implement them later this week.

**Comment by davet2001** [comment]
It’s great that you’ve done this but I think this issue is no longer a problem as synctrayzor seems to deal with it well. 

It is also directly linked from the syncthing download page.

So from my point of view this ticket can be closed.
